name: drink_water_app
description: "一款简洁美观的智能饮水APP - 快速接水，轻松生活"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  
  # UI
  cupertino_icons: ^1.0.8
  ionicons: ^0.2.2
  flutter_svg: ^2.0.17
  google_fonts: ^6.2.1
  lottie: ^3.3.1
  
  # 状态管理
  get: ^4.7.2
  
  # 网络
  dio: ^5.8.0+1
  
  # 本地存储
  shared_preferences: ^2.5.2
  
  # 工具
  enhanced_future_builder: ^2.0.0
  modal_bottom_sheet: ^3.0.0
  
  # 扫码
  qr_code_scanner:
    git: https://github.com/wizmea/qr_code_scanner.git
  
  # 权限
  permission_handler: ^12.0.1
  
  # URL 打开
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon_new.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/app_icon_new.png"
    background_color: "#hex_code"
    theme_color: "#hex_code"
  windows:
    generate: true
    image_path: "assets/icons/app_icon_new.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/app_icon_new.png"

